flickr8k_audio_dir = "/share/data/lang/users/kamperh/flickr_multimod/flickr_audio/"
flickr8k_text_dir = "/share/data/lang/users/kamperh/flickr_multimod/Flickr8k_text/"
# mscoco_json_fn = "/share/data/lang/users/spsettle/tf-common/multimodal/datasets/mscoco/coco_raw_all.json"
mscoco_annotations_dir = "/share/data/lang/users/spsettle/tf-common/multimodal/datasets/mscoco/coco/annotations/"
flickr30k_dir = "/share/data/vision-greg/flickr30k/"
